### ISSUE TITLE
Setup a new organization to host everything related to kazcontent

### ISSUE THREAD

**Issue by igibek** [kassenov/kaz-nlp#2]
I propose to set up a separate organization as a part of an effort to increase the IT content in the Kazakh language. All repositories, translation efforts, and so on will be hosted in the organization. In this way, it will be easier to promote the project and recruit new contributors. 

Any thoughts?

**Comment by arpanetus** [comment]
I think it's a wonderful proposal, I'm all in.

**Comment by kassenov** [comment]
The org was created and we've moved there.
